name: WorldeditRegions
main: com.empcraft.wrg.WorldeditRegions
version: 1.0.1
depend: [WorldEdit]
softdepend: [WGCustomFlags,Vault,WorldGuard,GriefPrevention,PreciousStones,Towny,Factions,Residence]
commands:
   wrg:
      description: All Worldedit Regions Commands