name: WorldeditRegions
main: com.empcraft.wrg.WorldeditRegions
version: 1.0.5
depend: [WorldEdit]
softdepend: [Vault,WorldGuard]
commands:
   wrg:
      description: All Worldedit Regions Commands
      aliases: [worldeditregions,wer,wr]
