name: WorldeditRegions
main: com.empcraft.WorldeditRegions
version: 0.2.4
depend: [WorldEdit]
softdepend: [WorldGuard,GriefPrevention,PreciousStones,Towny,Factions,Residence]
commands:
   wrg:
      description: All Worldedit Regions Commands